version: "3.9"

services:
  bug:
    build: .
    environment:
      PORT_API: 9000
      PORT_GAME_SERVER: 4500
    ports:
      - '4500:4500'
      - '9000:9000'
    networks:
      - bugw

  bugs:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bugw

networks:
  bugw:
    driver: bridge