version: "3.9"

services:
  api:
    build: .
    environment:
      PORT_API: 9000
      PORT_GAME_SERVER: 4500
    ports:
      - '4500:4500'
      - '9000:9000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge