version: "3.9"

services:
  serverapi:
    build: .
    environment:
      PORT_API: 9000
      PORT_GAME_SERVER: 4500
    ports:
      - '4500:4500'
      - '9000:9000'
    networks:
      - servernetwork

  webserver:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/ssl:/cert
      - ./html:/usr/share/nginx/html
    networks:
      - servernetwork

networks:
  servernetwork:
    driver: bridge