version: "3.9"

services:
  gameapi:
    build: .
    environment:
      PORT_API: 9000
      PORT_GAME_SERVER: 4500
    ports:
      - '4500:4500'
      - '9000:9000'
    networks:
      - mynetwork

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge